Feature/typoscript-merge_configs
dkdeploy/dkdeploy.github.io pull request #27
Opened 2017-04-19 14:07 UTC by CuyGuy

This adds documentation for tasks "merge_configs" and "merge_config_in_base_path"

2017-04-19 14:24 UTC, klyonrad requested changes
👍 

also, please squash your changes into one commit afterwards

2017-04-19 14:24 UTC, klyonrad commented on rake/dkdeploy-typo3-cms/typoscript.md
> +Example: ```customer_extension/Configuration/Typoscript/Config/Stages/config.#{fetch(:stage)}.txt```
please use single backticks

2017-04-19 14:24 UTC, klyonrad commented on rake/dkdeploy-typo3-cms/typoscript.md
> + This task is called by <a href="#mergeconfiginbasepath">merge_config_in_base_path</a>, so you may not need to call it yourself.
please remove all of the hrefs, we might about hyperlinks to other tasks for the whole page in a separate issue

just the task name with single back ticks :)

2017-04-19 15:04 UTC, CuyGuy commented on rake/dkdeploy-typo3-cms/typoscript.md
> +Example: ```customer_extension/Configuration/Typoscript/Config/Stages/config.#{fetch(:stage)}.txt```
OK, fixed that

2017-04-19 15:04 UTC, CuyGuy commented on rake/dkdeploy-typo3-cms/typoscript.md
> + This task is called by <a href="#mergeconfiginbasepath">merge_config_in_base_path</a>, so you may not need to call it yourself.
Removed all <a> Tags

2017-04-19 15:07 UTC, CuyGuy commented
Updated Pull Request according to the requested changes - please review again

2017-04-20 08:29 UTC, klyonrad approved these changes

2017-04-20 12:53 UTC, klyonrad commented
Sorry @CuyGuy can you resolve the merge/rebase conflicts please? I'm having a tough time with it...

2017-04-21 08:04 UTC, CuyGuy commented
resolved the merge conflict and updated the pull request, please check again

2017-04-21 08:20 UTC, klyonrad approved these changes
thanks a lot 😃

2017-04-21 08:21 UTC, merged